# Generated by Django 4.1.7 on 2023-02-28 03:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 3, 18, 29, 975413)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.menu', verbose_name='Родительский элемент'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='visible',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='1', max_length=2, verbose_name='Видимость'),
        ),
    ]
